// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAiUsage: (force: boolean | null) => typedError<AiUsageSnapshot, string>(__TAURI_INVOKE("get_ai_usage", { force })),
	connectOpenrouterOauth: () => typedError<null, string>(__TAURI_INVOKE("connect_openrouter_oauth")),
	startScan: (onEvent: Channel<ScanEvent>, categories: Category[] | null) => typedError<ScanResult, string>(__TAURI_INVOKE("start_scan", { onEvent, categories })),
	getLastScan: () => __TAURI_INVOKE<{
	scan_id: string,
	started_at: number,
	finished_at: number,
	categories: CategoryResult[],
	total_bytes: number,
	safe_bytes: number,
	rebuild_bytes: number,
	manual_bytes: number,
} | null>("get_last_scan"),
	createDeletePlan: (scanId: string, selectedItemIds: string[]) => typedError<PlanPreview, string>(__TAURI_INVOKE("create_delete_plan", { scanId, selectedItemIds })),
	executeClean: (planId: string, onEvent: Channel<CleanEvent>) => typedError<CleanResult, string>(__TAURI_INVOKE("execute_clean", { planId, onEvent })),
	getMemoryMetrics: () => typedError<MemoryMetrics, string>(__TAURI_INVOKE("get_memory_metrics")),
	terminateProcessGroup: (name: string, force: boolean) => typedError<number, string>(__TAURI_INVOKE("terminate_process_group", { name, force })),
	pickKeepAwakeApplication: () => typedError<{
	name: string,
	executable_pattern: string,
	path: string,
} | null, string>(__TAURI_INVOKE("pick_keep_awake_application")),
	getDiskMetrics: () => typedError<DiskMetrics, string>(__TAURI_INVOKE("get_disk_metrics")),
	getDiskVolumes: () => __TAURI_INVOKE<DiskVolume[]>("get_disk_volumes"),
	openDiskUtility: () => typedError<null, string>(__TAURI_INVOKE("open_disk_utility")),
	getDockerStatus: () => typedError<DockerStatus, string>(__TAURI_INVOKE("get_docker_status")),
	pruneDockerTarget: (signatureId: string) => typedError<number, string>(__TAURI_INVOKE("prune_docker_target", { signatureId })),
	getLocalModels: () => typedError<LocalModelItem[], string>(__TAURI_INVOKE("get_local_models")),
	deleteLocalModel: (modelId: string) => typedError<number, string>(__TAURI_INVOKE("delete_local_model", { modelId })),
	getAwakeState: () => typedError<AwakeState, string>(__TAURI_INVOKE("get_awake_state")),
	setAwakeRules: (rules: AwakeRule[]) => typedError<null, string>(__TAURI_INVOKE("set_awake_rules", { rules })),
	setManualAwake: (durationSecs: number | null, behavior: AwakeBehavior) => typedError<null, string>(__TAURI_INVOKE("set_manual_awake", { durationSecs, behavior })),
	disableManualAwake: () => typedError<null, string>(__TAURI_INVOKE("disable_manual_awake")),
	getSettings: () => typedError<ZenithSettings_Serialize, string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: ZenithSettings_Deserialize) => typedError<null, string>(__TAURI_INVOKE("save_settings", { settings })),
	revealInFinder: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_finder", { path })),
	openDashboardWindow: () => typedError<null, string>(__TAURI_INVOKE("open_dashboard_window")),
	getAppVersion: () => __TAURI_INVOKE<string>("get_app_version"),
	toggleQuickPanel: () => typedError<null, string>(__TAURI_INVOKE("toggle_quick_panel")),
	getDiagnostics: () => typedError<DiagnosticsSnapshot, string>(__TAURI_INVOKE("get_diagnostics")),
	openLogsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_logs_folder")),
};

/* Types */
export type AiProviderUsage = {
	id: string,
	name: string,
	installed: boolean,
	connected: boolean,
	auth_label: string,
	status_message: string,
	support: UsageSupport,
	windows: UsageWindow[],
	summary: UsageSummary,
	action_url: string | null,
};

export type AiUsageSnapshot = {
	providers: AiProviderUsage[],
	fetched_at: number,
};

export type AwakeBehavior = "prevent_system_sleep" | "keep_display_awake";

export type AwakeRule = {
	id: string,
	app_name: string,
	executable_pattern: string,
	behavior: AwakeBehavior,
	power_condition?: PowerCondition,
	enabled: boolean,
};

export type AwakeRuleEvaluation = {
	rule_id: string,
	status: AwakeRuleStatus,
	is_process_running: boolean,
	is_power_eligible: boolean,
};

export type AwakeRuleStatus = "active" | "waiting_process" | "waiting_power" | "disabled";

export type AwakeState = {
	is_active: boolean,
	behavior: AwakeBehavior | null,
	trigger_source: string | null,
	active_process_name: string | null,
	active_rule_id: string | null,
	manual_expires_at: number | null,
	active_rules_count: number,
	power_source: PowerSourceType,
	last_error: string | null,
	rule_evaluations: AwakeRuleEvaluation[],
};

export type Category = "ai" | "developer" | "container" | "model" | "system";

export type CategoryResult = {
	category: Category,
	display_name: string,
	items: ScanItem[],
	total_bytes: number,
	safe_bytes: number,
	rebuild_bytes: number,
	manual_bytes: number,
};

export type CleanEvent = { type: "Started"; plan_id: string; total_targets: number; expected_bytes: number } | { type: "ItemStarted"; item_id: string; name: string; index: number; total: number } | { type: "ItemFinished"; item_id: string; name: string; success: boolean; reclaimed_bytes: number; error: string | null } | { type: "Finished"; result: CleanResult } | { type: "Error"; message: string };

export type CleanFailureReason = "permission_denied" | "changed_since_scan" | "not_found" | "in_use" | "blacklisted" | "external_command_failed" | "unknown";

export type CleanItemResult = {
	item_id: string,
	name: string,
	path: string,
	status: CleanStatus,
	success: boolean,
	bytes_reclaimed: number,
	failure_reason: CleanFailureReason | null,
	error_message: string | null,
};

export type CleanResult = {
	plan_id: string,
	started_at: number,
	finished_at: number,
	total_reclaimed_bytes: number,
	total_failed_bytes: number,
	items: CleanItemResult[],
	actual_disk_free_delta: number | null,
};

export type CleanStatus = "success" | "partial" | "failed";

export type DashboardTab = DashboardTab_Serialize | DashboardTab_Deserialize;

export type DashboardTab_Deserialize = "disk" | "storage" | "docker" | "models" | "memory" | "usage" | "awake";

export type DashboardTab_Serialize = "disk" | "storage" | "docker" | "models" | "memory" | "usage" | "awake";

export type DiagnosticsSnapshot = {
	app_version: string,
	os_version: string,
	arch: string,
	log_path: string,
	enabled_features: string[],
	recent_errors: string[],
	settings_corrupt_recovered: boolean,
};

export type DiskMetrics = {
	mount_point: string,
	total_bytes: number,
	used_bytes: number,
	free_bytes: number,
	available_bytes: number,
	percent_used: number | null,
};

export type DiskVolume = {
	name: string,
	mount_point: string,
	file_system: string,
	disk_type: string,
	total_bytes: number,
	used_bytes: number,
	available_bytes: number,
	percent_used: number | null,
	is_removable: boolean,
	is_primary: boolean,
};

export type DockerContainerItem = {
	id: string,
	name: string,
	image: string,
	state: string,
	size_bytes: number,
	is_running: boolean,
};

export type DockerImageItem = {
	id: string,
	repository: string,
	tag: string,
	size_bytes: number,
	is_dangling: boolean,
	is_in_use: boolean,
};

export type DockerOverview = {
	images: DockerResourceUsage,
	containers: DockerResourceUsage,
	volumes: DockerResourceUsage,
	build_cache: DockerResourceUsage,
	total_bytes: number,
	total_reclaimable_bytes: number,
	safe_cleanable_bytes: number,
};

export type DockerResourceUsage = {
	total_bytes: number,
	reclaimable_bytes: number,
};

export type DockerStatus = {
	is_available: boolean,
	is_running: boolean,
	version: string | null,
	error_message: string | null,
	overview: DockerOverview | null,
	images: DockerImageItem[],
	containers: DockerContainerItem[],
	volumes: DockerVolumeItem[],
};

export type DockerVolumeItem = {
	name: string,
	driver: string,
	size_bytes: number,
	is_in_use: boolean,
};

export type FileSize = {
	logical: number,
	allocated: number | null,
};

export type LocalModelItem = {
	id: string,
	name: string,
	source: ModelSource,
	path: string,
	size_bytes: number,
	format: string | null,
	parameter_size: string | null,
	quantization: string | null,
	last_modified: number | null,
};

export type MemoryMetrics = {
	total_bytes: number,
	used_bytes: number,
	available_bytes: number,
	free_bytes: number,
	compressed_bytes: number,
	swap_used_bytes: number,
	swap_total_bytes: number,
	pressure: MemoryPressure,
	top_processes: ProcessMemory[],
	timestamp: number,
};

export type MemoryPressure = "normal" | "warning" | "critical";

export type ModelSource = "ollama" | "huggingface" | "lmstudio" | "mlx";

export type PlanPreview = {
	id: string,
	targets: PlanTargetPreview[],
	expected_reclaim_bytes: number,
	risk: RiskSummary,
	expires_at: number,
};

export type PlanTargetPreview = {
	item_id: string,
	name: string,
	expected_bytes: number,
	risk: RiskTier,
};

export type PowerCondition = "always" | "ac_power_only";

export type PowerSourceType = "ac" | "battery" | "unknown";

export type ProcessMemory = {
	pid: number,
	pids?: number[],
	name: string,
	memory_bytes: number,
	process_count: number,
	can_terminate: boolean,
};

export type QuickPanelSection = "storage" | "cleanup" | "ai_usage" | "categories" | "memory";

export type RiskSummary = {
	safe_count: number,
	rebuild_count: number,
	manual_count: number,
	safe_bytes: number,
	rebuild_bytes: number,
	manual_bytes: number,
};

export type RiskTier = "safe" | "rebuild" | "manual";

export type ScanEvent = { type: "Started"; scan_id: string } | { type: "CategoryStarted"; category: Category } | { type: "ItemFound"; item: ScanItem } | { type: "CategoryFinished"; category: Category; bytes: number; item_count: number } | { type: "Finished"; result: ScanResult } | { type: "Error"; message: string };

export type ScanItem = {
	id: string,
	signature_id: string,
	name: string,
	category: Category,
	risk: RiskTier,
	path: string,
	size: FileSize,
	file_count: number,
	description: string,
	is_selected: boolean,
	last_modified: number | null,
	exists: boolean,
};

export type ScanResult = {
	scan_id: string,
	started_at: number,
	finished_at: number,
	categories: CategoryResult[],
	total_bytes: number,
	safe_bytes: number,
	rebuild_bytes: number,
	manual_bytes: number,
};

export type SelectedApplication = {
	name: string,
	executable_pattern: string,
	path: string,
};

export type UsageSummary = {
	lifetime_tokens: number | null,
	last_7d_tokens: number | null,
	peak_daily_tokens: number | null,
	current_streak_days: number | null,
	local_sessions: number | null,
	local_cost_usd: number | null,
	usage_usd: number | null,
	limit_remaining_usd: number | null,
};

export type UsageSupport = "live" | "local" | "manual";

export type UsageWindow = {
	label: string,
	used_percent: number | null,
	resets_at: number | null,
};

export type ZenithSettings = ZenithSettings_Serialize | ZenithSettings_Deserialize;

export type ZenithSettings_Deserialize = {
	launch_at_login?: boolean,
	clean_ai_tools?: boolean,
	clean_developer_tools?: boolean,
	clean_docker?: boolean,
	clean_local_models?: boolean,
	include_rebuild_caches?: boolean,
	theme?: string,
	excluded_signatures?: string[],
	awake_rules?: AwakeRule[],
	quick_panel_sections?: QuickPanelSection[],
	quick_panel_ai_providers?: string[],
	dashboard_tabs?: DashboardTab_Deserialize[],
};

export type ZenithSettings_Serialize = {
	launch_at_login: boolean,
	clean_ai_tools: boolean,
	clean_developer_tools: boolean,
	clean_docker: boolean,
	clean_local_models: boolean,
	include_rebuild_caches: boolean,
	theme: string,
	excluded_signatures: string[],
	awake_rules: AwakeRule[],
	quick_panel_sections: QuickPanelSection[],
	quick_panel_ai_providers: string[],
	dashboard_tabs: DashboardTab_Serialize[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

