//! The capability contract for the desktop command surface.
//!
//! A Tauri command that no capability grants is invisible to the front end: the
//! IPC call is rejected at runtime, and the rejection surfaces as a swallowed
//! error in whichever store called it, on a window this suite never drives.
//! Three committed artefacts decide that outcome — the `COMMANDS` array in
//! `build.rs`, the generated permissions under `permissions/autogenerated/`,
//! and the capability JSON under `capabilities/` — and they are only useful
//! together. Reading them as one document makes a grant that names nothing, a
//! command that no window grants, and a panel that quietly gained write
//! authority fail the suite instead of shipping.
//!
//! No test here starts a Tauri runtime: the contract is manifest data, and a
//! check that needed a window would not run where the manifests are reviewed.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

/// The commands the quick (menu-bar) window may invoke.
///
/// The rule for this window is read-mostly: metrics and status reads, scan
/// observation, the backend-owned safe cleanup (`quick_clean_safe` selects the
/// backend's own Safe-tier candidates and cannot be pointed at an arbitrary
/// target), platform vocabulary, and navigation between Zenith's own windows.
/// Nothing here hands the panel a cleaner, a planner, or a settings writer, so
/// a permission added to `capabilities/quick.json` has to be added here too —
/// that edit is the review, and it is the only way past
/// [`quick_window_grants_only_reviewed_read_mostly_permissions`].
const QUICK_WINDOW_PERMISSIONS: [&str; 17] = [
    "allow-get-ai-usage",
    "allow-get-ai-provider-descriptors",
    "allow-get-ai-control-quick-summary",
    "allow-get-agent-quick-summary",
    "allow-start-scan",
    "allow-get-last-scan",
    "allow-quick-clean-safe",
    "allow-get-memory-metrics",
    "allow-get-disk-metrics",
    "allow-get-disk-volumes",
    "allow-get-awake-state",
    "allow-get-settings",
    "allow-get-platform-capabilities",
    "allow-get-platform-context",
    "allow-open-dashboard-window",
    "allow-toggle-quick-panel",
    "allow-get-app-version",
];

/// Command permissions that change machine or persistent state, spawn a
/// process, or end one.
///
/// The quick window's allowlist is compared against this list as well as
/// against an exact set, because the two guards fail differently: the exact set
/// catches any unreviewed grant, and this one still refuses a mutating grant
/// that was recorded in [`QUICK_WINDOW_PERMISSIONS`] in the same commit. A
/// permission that a rename retires is caught by
/// [`mutation_guards_name_permissions_the_build_generates`], so the list cannot
/// rot into an empty set of comparisons.
const MUTATING_PERMISSIONS: [&str; 23] = [
    "allow-create-delete-plan",
    "allow-execute-clean",
    "allow-execute-trash-plan",
    "allow-prepare-large-file-trash",
    "allow-prepare-app-uninstall",
    "allow-delete-local-model",
    "allow-prune-docker-target",
    "allow-terminate-memory-group",
    "allow-save-settings",
    "allow-save-ai-control-preferences",
    "allow-delete-ai-provider-credential",
    "allow-connect-openrouter-oauth",
    "allow-start-large-file-scan",
    "allow-setup-agent-integration",
    "allow-remove-agent-integration",
    "allow-set-awake-rules",
    "allow-set-manual-awake",
    "allow-disable-manual-awake",
    "allow-register-developer-home-workspace",
    "allow-open-in-terminal",
    "allow-post-agent-event",
    "allow-request-stop-agent-session",
    "allow-release-development-listener",
];

/// Registered commands the main window deliberately does not grant.
///
/// The main window owns every workflow, so a command missing from
/// `capabilities/main.json` is normally a defect — but `quick_clean_safe` has
/// exactly one caller, the menu-bar panel, and the dashboard has no surface
/// that reaches it. Granting it to `main` as well would widen that window's
/// authority for a caller that does not exist, so the exemption is recorded
/// here instead of being hidden in the difference between two files.
const MAIN_WINDOW_EXEMPT_PERMISSIONS: [&str; 1] = ["allow-quick-clean-safe"];

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}

/// The value between the first pair of quotes on `line`, when the line holds
/// exactly one quoted value. A second literal means the generated file declares
/// more than one command for a permission this suite assumes is 1:1.
fn single_quoted(line: &str) -> Option<String> {
    let open = line.find('"')?;
    let after = &line[open + 1..];
    let close = after.find('"')?;
    if after[close + 1..].contains('"') {
        return None;
    }
    Some(after[..close].to_string())
}

/// The generated permission files, keyed by the command each one enables.
///
/// The identifier is read from inside the file rather than from its name: the
/// capability JSON names identifiers, so a stale file name would otherwise let
/// a grant resolve against a command the file no longer declares.
fn generated_commands() -> BTreeMap<String, String> {
    let dir = manifest_dir().join("permissions/autogenerated");
    let mut paths: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|error| panic!("read {}: {error}", dir.display()))
        .map(|entry| {
            entry
                .unwrap_or_else(|error| panic!("read an entry of {}: {error}", dir.display()))
                .path()
        })
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "toml")
        })
        .collect();
    paths.sort();

    assert!(
        !paths.is_empty(),
        "{} declares no permission files; tauri-build generates one per registered command",
        dir.display()
    );

    let mut commands = BTreeMap::new();
    for path in &paths {
        let source = read(path);
        let permission = source
            .lines()
            .find(|line| line.starts_with("identifier = \"allow-"))
            .and_then(single_quoted)
            .unwrap_or_else(|| {
                panic!(
                    "{} must declare one `identifier = \"allow-…\"`; regenerate the permissions",
                    path.display()
                )
            });
        let command = source
            .lines()
            .find(|line| line.starts_with("commands.allow = ["))
            .and_then(single_quoted)
            .unwrap_or_else(|| {
                panic!(
                    "{} must enable exactly one command via `commands.allow = [\"…\"]`",
                    path.display()
                )
            });

        let replaced = commands.insert(command.clone(), permission.clone());
        assert!(
            replaced.is_none(),
            "`{command}` is enabled by two generated permissions; \
             regenerate the permissions instead of resolving the collision by hand"
        );
    }
    commands
}

/// The commands `build.rs` hands to `tauri_build::AppManifest::new().commands`.
///
/// The registration list is the contract source because it is the only place a
/// command can enter the IPC surface: tauri-build derives the permission
/// identifiers under `permissions/autogenerated/` from exactly this array, so
/// everything below — the generated grant, the capability that must name it —
/// is downstream of it. The parse fails loudly instead of returning an empty
/// list, because an empty registration list would make every coverage
/// assertion in this file vacuously true.
fn registered_commands() -> Vec<String> {
    let path = manifest_dir().join("build.rs");
    let source = read(&path);
    let marker = "const COMMANDS: &[&str] = &[";
    let start = source.find(marker).unwrap_or_else(|| {
        panic!(
            "{} must declare `{marker}`; the registration list moved and this suite no longer reads it",
            path.display()
        )
    });
    let body = &source[start + marker.len()..];
    let end = body.find("];").unwrap_or_else(|| {
        panic!(
            "{}: the COMMANDS array literal must be closed",
            path.display()
        )
    });
    let body = &body[..end];

    let mut commands = Vec::new();
    let mut rest = body;
    while let Some(open) = rest.find('"') {
        let after = &rest[open + 1..];
        let close = after.find('"').unwrap_or_else(|| {
            panic!(
                "{}: unterminated string literal in COMMANDS",
                path.display()
            )
        });
        let literal = &after[..close];
        assert!(
            !literal.contains('\\'),
            "COMMANDS entries must be plain literals; `{literal}` needs a real parser"
        );
        commands.push(literal.to_string());
        rest = &after[close + 1..];
    }

    assert!(
        !commands.is_empty(),
        "{}: the COMMANDS array literal parsed to zero commands",
        path.display()
    );
    commands
}

/// The `allow-*` entries of one capability file, by file name under
/// `capabilities/`.
fn capability_permissions(file: &str) -> BTreeSet<String> {
    let path = manifest_dir().join("capabilities").join(file);
    let raw = read(&path);
    let json: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|error| panic!("{} is not valid JSON: {error}", path.display()));
    let entries = json
        .get("permissions")
        .and_then(serde_json::Value::as_array)
        .unwrap_or_else(|| panic!("{} must carry a `permissions` array", path.display()));

    let granted: BTreeSet<String> = entries
        .iter()
        .map(|entry| {
            entry
                .as_str()
                .unwrap_or_else(|| panic!("{}: every permission must be a string", path.display()))
                .to_string()
        })
        .filter(|permission| permission.starts_with("allow-"))
        .collect();

    assert!(
        !granted.is_empty(),
        "{} grants no command permission; the file was renamed or emptied",
        path.display()
    );
    granted
}

/// A capability file may only name permissions the build actually generates: a
/// typo, or a grant left behind by a deleted command, is refused here rather
/// than at the IPC call that finds nothing behind it.
#[test]
fn every_granted_permission_is_generated_by_the_build() {
    let generated: BTreeSet<String> = generated_commands().into_values().collect();

    for file in ["main.json", "quick.json"] {
        let unstructured: Vec<String> = capability_permissions(file)
            .difference(&generated)
            .cloned()
            .collect();
        assert!(
            unstructured.is_empty(),
            "capabilities/{file} grants permissions no registered command declares: {unstructured:?}"
        );
    }
}

/// Every registered command reaches the main window.
///
/// The main window is the reviewed surface that owns every workflow, so a
/// command that is registered but ungranted would fail only when a user opens
/// the dashboard and clicks — the slowest possible feedback for the cheapest
/// possible mistake. The exemption list is part of the assertion, so the gap it
/// covers is exactly the gap that was reviewed.
#[test]
fn every_registered_command_is_granted_to_the_main_window() {
    let generated = generated_commands();

    let ungenerated: Vec<String> = registered_commands()
        .into_iter()
        .filter(|command| !generated.contains_key(command))
        .collect();
    assert!(
        ungenerated.is_empty(),
        "build.rs registers commands with no generated permission; run the tauri-build \
         permission step and commit the result: {ungenerated:?}"
    );

    let main = capability_permissions("main.json");
    let ungranted: BTreeSet<String> = generated
        .values()
        .filter(|permission| !main.contains(*permission))
        .cloned()
        .collect();
    let exempt: BTreeSet<String> = MAIN_WINDOW_EXEMPT_PERMISSIONS
        .iter()
        .map(|permission| permission.to_string())
        .collect();

    assert_eq!(
        ungranted, exempt,
        "capabilities/main.json must grant every registered command except the reviewed \
         exemptions"
    );
}

/// The quick window holds exactly the reviewed read-mostly allowlist.
///
/// Equality in both directions is the point: an added permission fails until
/// it is recorded in the constant, and a removed one fails too, so the constant
/// cannot drift away from the file it describes.
#[test]
fn quick_window_grants_only_reviewed_read_mostly_permissions() {
    let quick = capability_permissions("quick.json");
    let reviewed: BTreeSet<String> = QUICK_WINDOW_PERMISSIONS
        .iter()
        .map(|permission| permission.to_string())
        .collect();

    let unreviewed: Vec<String> = quick.difference(&reviewed).cloned().collect();
    assert!(
        unreviewed.is_empty(),
        "capabilities/quick.json grants permissions the reviewed read-mostly allowlist does \
         not name; review them and extend QUICK_WINDOW_PERMISSIONS: {unreviewed:?}"
    );

    let dropped: Vec<String> = reviewed.difference(&quick).cloned().collect();
    assert!(
        dropped.is_empty(),
        "QUICK_WINDOW_PERMISSIONS names permissions capabilities/quick.json no longer \
         grants: {dropped:?}"
    );

    let mut mutating: Vec<String> = quick
        .iter()
        .filter(|permission| MUTATING_PERMISSIONS.contains(&permission.as_str()))
        .cloned()
        .collect();
    mutating.sort();
    assert!(
        mutating.is_empty(),
        "the quick window must not hold mutation authority, even when the allowlist is \
         edited in the same commit: {mutating:?}"
    );
}

/// The guard lists name commands the build still generates.
///
/// Both lists above are consulted by name, so a rename would leave them
/// comparing against nothing and passing. This keeps every entry load-bearing.
#[test]
fn mutation_guards_name_permissions_the_build_generates() {
    let generated: BTreeSet<String> = generated_commands().into_values().collect();

    let retired: Vec<&str> = MUTATING_PERMISSIONS
        .iter()
        .chain(MAIN_WINDOW_EXEMPT_PERMISSIONS.iter())
        .copied()
        .filter(|permission| !generated.contains(*permission))
        .collect();
    assert!(
        retired.is_empty(),
        "these guard entries name permissions no registered command declares; rename them \
         with the command they were written for: {retired:?}"
    );
}
