// Re-export generated types from Tauri Specta bindings
export type {
  AgentActivitySnapshot,
  AgentActivityStatus,
  AgentAdapterHealth,
  AgentAdapterState,
  AgentEvidence,
  AgentIntegrationInfo,
  AgentIntegrationResult,
  AgentLifecycleEvent,
  AgentNotificationPreferences,
  AgentQuickSessionRow,
  AgentQuickSummary,
  AgentSession,
  AttentionReason,
  ApplicationIdentity,
  IngestedAgentEvent,
  AwakeAgentId,
  AppInstallSource,
  AppRelatedConfidence,
  AppRelatedItem,
  AppRelatedKind,
  AppUninstallInspection,
  AwakeBehavior,
  AwakeRule,
  AwakeRuleEvaluation,
  AwakeRuleStatus,
  AwakeState,
  AuditEntry,
  AutopilotPreferences,
  BudgetPeriod,
  BudgetStatus,
  Category,
  CategoryResult,
  CacheArtifactKind,
  CacheManagementMode,
  CacheMetadata,
  CacheUsageConfidence,
  CacheSizeSemantics,
  CleanEvent,
  CleanFailureReason,
  CleanItemResult,
  CleanResult,
  CleanStatus,
  ControlCenterQuickSummary,
  DashboardTab_Deserialize,
  DashboardTab_Serialize,
  DevelopmentListener,
  DeveloperArtifact,
  DeveloperArtifactKind,
  DeveloperArtifactScanEvent,
  DeveloperArtifactScanResult,
  DeveloperArtifactStatus,
  DeveloperArtifactUninspected,
  DeveloperArtifactUninspectedReason,
  DeveloperEcosystem,
  DeveloperWorkspace,
  DiagnosticsSnapshot,
  EnvironmentReport,
  SelfCheckRow,
  DiskMetrics,
  DiskVolume,
  DockerContainerItem,
  DockerImageItem,
  DockerOverview,
  DockerResourceUsage,
  DockerStatus,
  DockerVolumeItem,
  FileSize,
  InstalledApp,
  LargeFileFilter,
  LargeFileItem,
  LargeFileKind,
  LargeFileScanEvent,
  LargeFileScanRequest,
  LargeFileScanResult,
  ListenerExposure,
  ListenerProtocol,
  LocalModelItem,
  LocalAlertBudget,
  ManualProviderUsage,
  MemoryMetrics,
  MemoryPressure,
  MemoryTerminationMode,
  MemoryTerminationOutcome,
  MemoryTerminationResult,
  MoneyMicros,
  NormalizedSafetyEvidence,
  ObservationPeriod,
  ObservationQuality,
  ObservationScope,
  ObservationSourceKind,
  ModelSource,
  PlanPreview,
  PlanTargetPreview,
  PowerCondition,
  PowerSourceType,
  ProcessMemory,
  ProcessOwnership,
  PlatformCapabilities,
  PlatformContext,
  PlatformFeatureCapability,
  PlatformFeatureStatus,
  PlatformKind,
  ProjectContext,
  ProjectIdentity,
  ProviderId_Deserialize,
  ProviderId_Serialize,
  ProviderDescriptor_Deserialize,
  ProviderDescriptor_Serialize,
  AiProviderUsage_Deserialize,
  AiProviderUsage_Serialize,
  AiUsageSnapshot_Deserialize,
  AiUsageSnapshot_Serialize,
  ProviderMetric,
  ProviderObservation,
  CredentialKind,
  QuickPanelSection,
  RecommendationKind,
  ReleaseDevelopmentListenerResult,
  ReleaseMode,
  ReleaseOutcome,
  RiskSummary,
  RiskTier,
  ResourceAttribution,
  SafetyFinding,
  SafetyFindingKind,
  SafetySnapshot,
  FindingSeverity,
  GitChangeSummary,
  ScanEvent,
  ScanItem,
  ScanResult,
  SnapshotQuality,
  SelectedApplication,
  TrashItemResult,
  TrashPlanPreview,
  TrashResult,
  UsageSummary,
  UsageSupport,
  UsageWindow,
  ZenithSettings_Deserialize,
  ZenithSettings_Serialize,
} from '../bindings/tauri';

import type {
  AiControlPreferences_Serialize,
  AiControlCenterSnapshot_Serialize,
  AiProviderUsage_Serialize,
  AiUsageSnapshot_Serialize,
  DashboardRoute_Serialize,
  DashboardTab_Serialize,
  ProviderDescriptor_Serialize,
  ProviderId_Serialize,
  Recommendation_Serialize,
  RecommendationPreview_Serialize,
  ZenithSettings_Serialize,
} from '../bindings/tauri';

// In the frontend runtime, settings, snapshots, and provider structures are always fully resolved/serialized shapes
export type ZenithSettings = ZenithSettings_Serialize;
export type AiControlPreferences = AiControlPreferences_Serialize;
export type DashboardTab = DashboardTab_Serialize;
export type DashboardRoute = DashboardRoute_Serialize;
export type Recommendation = Recommendation_Serialize;
export type RecommendationPreview = RecommendationPreview_Serialize;
export type AiControlCenterSnapshot = AiControlCenterSnapshot_Serialize;
export type ProviderId = ProviderId_Serialize;
export type AiProviderUsage = AiProviderUsage_Serialize;
export type AiUsageSnapshot = AiUsageSnapshot_Serialize;
export type ProviderDescriptor = ProviderDescriptor_Serialize;

// Frontend-specific helper types and aliases
export type AiProviderId = ProviderId;

export type CleanStrategy =
  | 'delete_contents'
  | 'delete_directory'
  | 'external_command'
  | 'docker_prune'
  | 'manual';
