//! Which paths hold state that generic cleanup must never treat as junk.
//!
//! An age rule answers "has anything in here changed recently?". That is a
//! question about caches and logs, and it is the wrong question for a database,
//! a credential store, an application bundle, or a lock file: those are
//! structured, they are frequently written by other processes, and removing one
//! of them costs the user data rather than cache warmth. A generic rule that
//! deleted them would be deleting the only copy of something.
//!
//! The classification is deliberately pure and name-shaped: it is the *shared*
//! rule both platforms and both boundaries (planning and execution) agree on,
//! and it cannot depend on a filesystem cache or on a platform API without
//! making an unprovable decision possible. The caller supplies the two facts
//! that are not in the name — whether the entry is a directory and whether it
//! is marked executable — because those come from metadata the platform layer
//! already read.
//!
//! This is a boundary, not a policy. A signature that legitimately owns a
//! disposable database would have to go through a specialized provider (its own
//! lifecycle, its own verification); nothing about a discovery rule may reach
//! past this classifier.

use serde::{Deserialize, Serialize};

/// What kind of structured state a path name identifies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "snake_case")]
pub enum StructuredStateKind {
    /// A database file (`*.sqlite`, `*.db`, `*.realm`, LevelDB tables).
    Database,
    /// A file that only means something alongside a database: write-ahead logs,
    /// shared-memory files, journals, and LevelDB manifests.
    DatabaseCompanion,
    /// A lock, lease, or pid file: evidence that something else is using the
    /// location right now.
    Lock,
    /// Credentials, keys, tokens, and the directories that hold them.
    Credential,
    /// Configuration and preference state that outlives the cache around it.
    Configuration,
    /// An application, framework, or library bundle: an installable object.
    ApplicationBundle,
    /// An executable image.
    Executable,
}

impl StructuredStateKind {
    /// The reason shown when this classification blocks a cleanup.
    pub fn display_name(&self) -> &'static str {
        match self {
            Self::Database => "database file",
            Self::DatabaseCompanion => "database companion file",
            Self::Lock => "lock or pid file",
            Self::Credential => "credential or key material",
            Self::Configuration => "configuration state",
            Self::ApplicationBundle => "application bundle",
            Self::Executable => "executable image",
        }
    }

    /// Whether the entry holds state that cannot be regenerated by the owner.
    pub fn is_irreplaceable(&self) -> bool {
        matches!(self, Self::Credential | Self::Configuration)
    }
}

/// The entry kind the caller observed, as far as the shared rule needs it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "snake_case")]
pub enum EntryKind {
    #[default]
    File,
    Directory,
    /// Neither a regular file nor a directory: a socket, a fifo, a device.
    Other,
}

/// The facts the classifier is allowed to use.
#[derive(Debug, Clone, Copy)]
pub struct PathFacts<'a> {
    /// The final path component, as the filesystem spells it.
    pub name: &'a str,
    pub entry_kind: EntryKind,
    /// Whether the platform marked the entry executable (POSIX mode bit, or a
    /// Windows executable image). A name alone cannot say this.
    pub executable: bool,
}

impl<'a> PathFacts<'a> {
    pub fn new(name: &'a str, entry_kind: EntryKind) -> Self {
        Self {
            name,
            entry_kind,
            executable: false,
        }
    }

    pub fn executable(mut self, executable: bool) -> Self {
        self.executable = executable;
        self
    }
}

/// Database and data-store file extensions.
const DATABASE_EXTENSIONS: [&str; 12] = [
    "sqlite", "sqlite3", "sqlitedb", "db", "db3", "realm", "mdb", "accdb", "duckdb", "ldb", "sst",
    "wallet",
];

/// Extensions and names that only mean something next to a database.
const COMPANION_SUFFIXES: [&str; 4] = ["-wal", "-shm", "-journal", "-log.old"];

/// LevelDB/SQLite store markers that are meaningless outside their directory.
const STORE_MARKERS: [&str; 3] = ["CURRENT", "MANIFEST", "LOG.old"];

const LOCK_EXTENSIONS: [&str; 5] = ["lock", "lockfile", "lck", "pid", "pidfile"];
const LOCK_NAMES: [&str; 2] = ["lock", ".lock"];

const CREDENTIAL_EXTENSIONS: [&str; 10] = [
    "keychain",
    "keychain-db",
    "pem",
    "key",
    "p12",
    "pfx",
    "jks",
    "keystore",
    "kdbx",
    "netrc",
];
const CREDENTIAL_NAMES: [&str; 9] = [
    "credentials.json",
    "auth.json",
    "secrets.json",
    "id_rsa",
    "id_ed25519",
    "id_ecdsa",
    "known_hosts",
    ".env",
    ".netrc",
];

const CONFIGURATION_EXTENSIONS: [&str; 9] = [
    "plist",
    "ini",
    "cfg",
    "conf",
    "toml",
    "yaml",
    "yml",
    "properties",
    "prefs",
];
const CONFIGURATION_NAMES: [&str; 5] = [
    "config.json",
    "settings.json",
    "state.json",
    "preferences.json",
    "manifest.json",
];

const BUNDLE_EXTENSIONS: [&str; 11] = [
    "app",
    "appex",
    "framework",
    "bundle",
    "xpc",
    "kext",
    "plugin",
    "dext",
    "photoslibrary",
    "imovielibrary",
    "sparsebundle",
];

/// Cache containers whose extension says "database" but whose content is
/// regenerated on demand.
///
/// Windows Explorer keeps its thumbnail and icon caches in `.db` files
/// (`thumbcache_<size>.db`, `iconcache_<n>.db`). They are caches by contract —
/// Windows rebuilds them the next time it needs a picture — so treating the
/// extension alone as evidence of user state would protect a regenerable cache
/// and report its bytes as permanently unreclaimable. The list is deliberately
/// closed: a name that is not here is judged by the database rule, because the
/// cost of being wrong in that direction is a cache the user can still clear by
/// other means, not a database someone deletes.
const DISPOSABLE_CACHE_STORE_PREFIXES: [&str; 2] = ["thumbcache_", "iconcache_"];

const EXECUTABLE_EXTENSIONS: [&str; 17] = [
    "exe", "dll", "sys", "com", "scr", "msi", "msp", "bat", "cmd", "ps1", "sh", "zsh", "bash",
    "command", "dylib", "so", "o",
];

/// Credential directories, matched on the entry's own name.
const CREDENTIAL_DIRECTORIES: [&str; 7] = [
    ".ssh",
    ".gnupg",
    ".aws",
    ".azure",
    ".kube",
    "keychains",
    "credentials",
];

/// Classifies a path component as structured state, or returns `None`.
///
/// Names are compared case-insensitively on both platforms: Windows folds case
/// by definition, and a case-insensitive APFS volume can spell the same cache
/// name either way, so a case-sensitive rule would be a rule that admits the
/// object it exists to protect.
pub fn classify_structured_state(facts: PathFacts<'_>) -> Option<StructuredStateKind> {
    let name = facts.name.trim();
    if name.is_empty() {
        return None;
    }
    let lower = name.to_ascii_lowercase();
    let extension = lower
        .rsplit_once('.')
        .map(|(_, extension)| extension)
        .unwrap_or_default();

    if facts.entry_kind == EntryKind::Directory {
        if BUNDLE_EXTENSIONS.contains(&extension) {
            return Some(StructuredStateKind::ApplicationBundle);
        }
        if CREDENTIAL_DIRECTORIES.contains(&lower.as_str()) {
            return Some(StructuredStateKind::Credential);
        }
        return None;
    }

    // Companoins first: their base extension is what makes them companions, and
    // a name-shaped rule cannot tell a WAL from the database it belongs to.
    if COMPANION_SUFFIXES
        .iter()
        .any(|suffix| lower.ends_with(suffix))
    {
        return Some(StructuredStateKind::DatabaseCompanion);
    }
    if LOCK_NAMES.contains(&lower.as_str()) || LOCK_EXTENSIONS.contains(&extension) {
        return Some(StructuredStateKind::Lock);
    }
    if STORE_MARKERS.contains(&name) || lower.starts_with("manifest-") {
        return Some(StructuredStateKind::DatabaseCompanion);
    }
    if CREDENTIAL_NAMES.contains(&lower.as_str()) || CREDENTIAL_EXTENSIONS.contains(&extension) {
        return Some(StructuredStateKind::Credential);
    }
    if DISPOSABLE_CACHE_STORE_PREFIXES
        .iter()
        .any(|prefix| lower.starts_with(prefix))
    {
        // A cache container that happens to use a database extension. It is
        // still acted on only because a signature names it and its age policy
        // is satisfied; this rule decides that it is a cache, not that it is
        // disposable anywhere it appears.
        return None;
    }
    if DATABASE_EXTENSIONS.contains(&extension) {
        return Some(StructuredStateKind::Database);
    }
    if CONFIGURATION_NAMES.contains(&lower.as_str())
        || CONFIGURATION_EXTENSIONS.contains(&extension)
    {
        return Some(StructuredStateKind::Configuration);
    }
    if EXECUTABLE_EXTENSIONS.contains(&extension) || facts.executable {
        return Some(StructuredStateKind::Executable);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file(name: &str) -> Option<StructuredStateKind> {
        classify_structured_state(PathFacts::new(name, EntryKind::File))
    }

    fn directory(name: &str) -> Option<StructuredStateKind> {
        classify_structured_state(PathFacts::new(name, EntryKind::Directory))
    }

    #[test]
    fn databases_and_their_companions_are_protected() {
        assert_eq!(file("Cache.db"), Some(StructuredStateKind::Database));
        assert_eq!(file("cache.sqlite"), Some(StructuredStateKind::Database));
        assert_eq!(file("store.sqlite3"), Some(StructuredStateKind::Database));
        assert_eq!(file("000123.ldb"), Some(StructuredStateKind::Database));

        assert_eq!(
            file("Cache.db-wal"),
            Some(StructuredStateKind::DatabaseCompanion)
        );
        assert_eq!(
            file("cache.sqlite-shm"),
            Some(StructuredStateKind::DatabaseCompanion)
        );
        assert_eq!(
            file("history-journal"),
            Some(StructuredStateKind::DatabaseCompanion)
        );
        assert_eq!(
            file("MANIFEST-000004"),
            Some(StructuredStateKind::DatabaseCompanion)
        );
        assert_eq!(
            file("CURRENT"),
            Some(StructuredStateKind::DatabaseCompanion)
        );
    }

    #[test]
    fn locks_credentials_and_configuration_are_protected() {
        assert_eq!(file("app.lock"), Some(StructuredStateKind::Lock));
        assert_eq!(file("LOCK"), Some(StructuredStateKind::Lock));
        assert_eq!(file("service.pid"), Some(StructuredStateKind::Lock));

        assert_eq!(file("auth.json"), Some(StructuredStateKind::Credential));
        assert_eq!(
            file("login.keychain-db"),
            Some(StructuredStateKind::Credential)
        );
        assert_eq!(file("id_ed25519"), Some(StructuredStateKind::Credential));
        assert_eq!(directory(".ssh"), Some(StructuredStateKind::Credential));

        assert_eq!(
            file("com.example.app.plist"),
            Some(StructuredStateKind::Configuration)
        );
        assert_eq!(
            file("settings.json"),
            Some(StructuredStateKind::Configuration)
        );
    }

    #[test]
    fn bundles_and_executables_are_protected() {
        assert_eq!(
            directory("Google Chrome for Testing.app"),
            Some(StructuredStateKind::ApplicationBundle)
        );
        assert_eq!(
            directory("Some.framework"),
            Some(StructuredStateKind::ApplicationBundle)
        );
        assert_eq!(file("setup.exe"), Some(StructuredStateKind::Executable));
        assert_eq!(file("libfoo.dylib"), Some(StructuredStateKind::Executable));

        // An executable bit with an unremarkable name is still an executable.
        assert_eq!(
            classify_structured_state(PathFacts::new("helper", EntryKind::File).executable(true)),
            Some(StructuredStateKind::Executable)
        );
        assert_eq!(
            classify_structured_state(PathFacts::new("helper", EntryKind::File)),
            None
        );
    }

    /// A cache container is not a database, however its extension reads.
    #[test]
    fn explorer_thumbnail_and_icon_caches_are_caches_not_databases() {
        for name in ["thumbcache_256.db", "THUMBCACHE_1024.DB", "iconcache_48.db"] {
            assert_eq!(file(name), None, "{name} is a regenerable cache");
        }

        // The exception is closed: any other `.db` is still structured state,
        // and the prefix has to be the whole leading name.
        for name in ["history.db", "places.sqlite", "my-thumbcache.db"] {
            assert_eq!(
                file(name),
                Some(StructuredStateKind::Database),
                "{name} is not one of the cache containers"
            );
        }
        // A name with no database extension was never protected by that rule.
        assert_eq!(file("thumbcache"), None);
    }

    #[test]
    fn case_is_folded_because_a_volume_may_fold_it_too() {
        assert_eq!(file("CACHE.DB"), Some(StructuredStateKind::Database));
        assert_eq!(file("Auth.JSON"), Some(StructuredStateKind::Credential));
        assert_eq!(
            directory("Something.APP"),
            Some(StructuredStateKind::ApplicationBundle)
        );
    }

    /// The classifier is the boundary that keeps a generic rule out of
    /// structured state, so ordinary cache and log shapes must stay clean.
    #[test]
    fn ordinary_cache_and_log_shapes_are_not_structured_state() {
        for name in [
            "com.spotify.client",
            "Cache_Data",
            "Code Cache",
            "GPUCache",
            "ShaderCache",
            "CacheStorage",
            "Service Worker",
            "logs",
            "session.log",
            "trace.json",
        ] {
            assert_eq!(
                directory(name),
                None,
                "{name} must not classify as a bundle"
            );
            assert_eq!(file(name), None, "{name} must not classify as a file kind");
        }
    }

    #[test]
    fn an_empty_name_is_never_a_verdict() {
        assert_eq!(file(""), None);
        assert_eq!(file("   "), None);
        assert_eq!(directory(""), None);
    }
}
