#!/usr/bin/env node

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PACKAGE_IDENTIFIER = 'jaeyoung0509.Zenith';
const MANIFEST_VERSION = '1.12.0';
const REPOSITORY_URL = 'https://github.com/jaeyoung0509/zenith';

function fail(message) {
  console.error(`Error: ${message}`);
  process.exit(1);
}

function parseArgs(argv) {
  const values = {};
  for (let index = 0; index < argv.length; index += 2) {
    const key = argv[index];
    const value = argv[index + 1];
    if (!key?.startsWith('--') || value === undefined) {
      fail('expected --version, --installer, and --output arguments');
    }
    values[key.slice(2)] = value;
  }
  return values;
}

function validateVersion(version) {
  if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
    fail(`invalid package version: ${version}`);
  }
}

function sha256(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex').toUpperCase();
}

function writeManifest(filePath, contents) {
  fs.writeFileSync(filePath, `${contents.trim()}\n`, 'utf8');
}

const args = parseArgs(process.argv.slice(2));
const version = args.version;
const installerPath = args.installer ? path.resolve(args.installer) : null;
const outputRoot = args.output ? path.resolve(args.output) : null;

if (!version || !installerPath || !outputRoot) {
  fail('expected --version, --installer, and --output arguments');
}
validateVersion(version);
if (!fs.statSync(installerPath, { throwIfNoEntry: false })?.isFile()) {
  fail(`installer does not exist: ${installerPath}`);
}

const installerName = 'Zenith-windows-x64-setup.exe';
if (path.basename(installerPath) !== installerName) {
  fail(`installer filename must be ${installerName}`);
}

const manifestDirectory = path.join(
  outputRoot,
  'manifests',
  'z',
  'jaeyoung0509',
  'Zenith',
  version,
);
fs.mkdirSync(manifestDirectory, { recursive: true });

const installerUrl = `${REPOSITORY_URL}/releases/download/v${version}/${installerName}`;
const installerHash = sha256(installerPath);

writeManifest(
  path.join(manifestDirectory, `${PACKAGE_IDENTIFIER}.yaml`),
  `# Generated by scripts/generate_winget_manifest.cjs
PackageIdentifier: ${PACKAGE_IDENTIFIER}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: ${MANIFEST_VERSION}`,
);

writeManifest(
  path.join(manifestDirectory, `${PACKAGE_IDENTIFIER}.installer.yaml`),
  `# Generated by scripts/generate_winget_manifest.cjs
PackageIdentifier: ${PACKAGE_IDENTIFIER}
PackageVersion: ${version}
InstallerType: nullsoft
Scope: user
MinimumOSVersion: 10.0.17763.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ElevationRequirement: elevationProhibited
ReleaseDate: ${new Date().toISOString().slice(0, 10)}
Installers:
- Architecture: x64
  InstallerUrl: ${installerUrl}
  InstallerSha256: ${installerHash}
  AppsAndFeaturesEntries:
  - DisplayName: Zenith
    Publisher: jaeyoung0509
    DisplayVersion: ${version}
    InstallerType: nullsoft
ManifestType: installer
ManifestVersion: ${MANIFEST_VERSION}`,
);

writeManifest(
  path.join(manifestDirectory, `${PACKAGE_IDENTIFIER}.locale.en-US.yaml`),
  `# Generated by scripts/generate_winget_manifest.cjs
PackageIdentifier: ${PACKAGE_IDENTIFIER}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: jaeyoung0509
PublisherUrl: ${REPOSITORY_URL}
PublisherSupportUrl: ${REPOSITORY_URL}/issues
Author: Zenith contributors
PackageName: Zenith
PackageUrl: ${REPOSITORY_URL}
License: MIT
LicenseUrl: ${REPOSITORY_URL}/blob/v${version}/LICENSE
Copyright: Copyright (c) 2026 Zenith contributors
ShortDescription: Local developer storage, process, AI usage, and power management utility.
Description: Zenith is a cross-platform desktop utility for reviewing developer storage, processes, local services, AI usage, and sleep-control state with explicit safety boundaries.
Tags:
- cleanup
- developer-tools
- storage
- system-utility
ReleaseNotesUrl: ${REPOSITORY_URL}/releases/tag/v${version}
ManifestType: defaultLocale
ManifestVersion: ${MANIFEST_VERSION}`,
);

console.log(`Generated WinGet manifests at ${manifestDirectory}`);
console.log(`Installer SHA256: ${installerHash}`);
